# Even Fibonacci numbers
# Problem 2
#
# Each new term in the Fibonacci sequence is generated by adding the
# evious two terms. By starting with 1 and 2, the first 10 terms will
# be:
#
# 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#
# By considering the terms in the Fibonacci sequence whose values
# do not exceed four million, find the sum of the even-valued terms.

def evenFib(num)
	fibonaccis = [1, 2]

	i = 0
	while fibonaccis.last < num
		fibonaccis << fibonaccis[i] + fibonaccis[i + 1]
		i += 1
	end

	fibonaccis.pop
	fibonaccis.select! { |n| n % 2 == 0 }.reduce(:+)
end

puts evenFib(4_000_000)
